name: health_in_hand
description: Disease awareness

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 3.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  sizer: ^2.0.15
  firebase_core: ^1.12.0
  curved_navigation_bar: ^1.0.3
  salomon_bottom_bar: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.7
  readmore: ^2.1.0
  api_cache_manager: ^1.0.1
  path_provider: ^2.0.3
  toast: ^0.1.5
  flutter_local_notifications: ^8.2.0
  provider: ^6.0.0
  http: ^0.13.3
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  audioplayers: ^0.20.1
  connectivity_plus: ^2.0.3
  timeago: ^3.1.0
  url_launcher: ^6.0.17
  pinput: ^1.2.2
  html: ^0.15.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+4


dev_dependencies:
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/audio/

  fonts:
    - family: NutinoSansBold
      fonts:
        - asset: fonts/nutinosans_bold.ttf

    - family: NutinoSansReg
      fonts:
        - asset: fonts/nutinosans_regular.ttf

    - family: NutinoSansSemiBold
      fonts:
        - asset: fonts/nutinosans_semibold.ttf

    - family: Museo Sans Cyrl
      fonts:
        - asset: fonts/Museo Sans Cyrl 900.ttf

    - family: Museo Sans Cyrl 500 Regular
      fonts:
        - asset: fonts/Museo Sans Cyrl 500 Regular.ttf


