///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyChangePasswordError = 'error';
const String _jsonKeyChangePasswordMessage = 'message';
const String _jsonKeyChangePasswordData = 'data';
const String _jsonKeyChangePasswordDataMessage = 'message';

class ChangePasswordData {
/*
{
  "message": "Password updated successfully."
}
*/

  String? message;
  Map<String, dynamic> __origJson = {};

  ChangePasswordData({
    this.message,
  });
  ChangePasswordData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    message = json[_jsonKeyChangePasswordDataMessage]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyChangePasswordDataMessage] = message;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class ChangePassword {
/*
{
  "error": false,
  "message": "list_success",
  "data": {
    "message": "Password updated successfully."
  },
  "meta": [
    null
  ]
}
*/

  bool? error;
  String? message;
  ChangePasswordData? data;
  List<ChangePassword>? meta;
  Map<String, dynamic> __origJson = {};

  ChangePassword({
    this.error,
    this.message,
    this.data,
    this.meta,
  });
  ChangePassword.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    error = json[_jsonKeyChangePasswordError];
    message = json[_jsonKeyChangePasswordMessage]?.toString();
    data = (json[_jsonKeyChangePasswordData] != null &&
            (json[_jsonKeyChangePasswordData] is Map))
        ? ChangePasswordData.fromJson(json[_jsonKeyChangePasswordData])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyChangePasswordError] = error;
    data[_jsonKeyChangePasswordMessage] = message;

      data[_jsonKeyChangePasswordData] = this.data!.toJson();

    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
