///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyDetailsOfTBError = 'error';
const String _jsonKeyDetailsOfTBMessage = 'message';
const String _jsonKeyDetailsOfTBData = 'data';
const String _jsonKeyDetailsOfTBMeta = 'meta';
const String _jsonKeyDetailsOfTBDataTbDetails = 'tb_details';
const String _jsonKeyDetailsOfTBDataTbDetailsId = 'id';
const String _jsonKeyDetailsOfTBDataTbDetailsComponentId = 'component_id';
const String _jsonKeyDetailsOfTBDataTbDetailsName = 'name';
const String _jsonKeyDetailsOfTBDataTbDetailsNameNe = 'name_ne';
const String _jsonKeyDetailsOfTBDataTbDetailsIsFaq = 'is_faq';
const String _jsonKeyDetailsOfTBDataTbDetailsOrderBy = 'order_by';
const String _jsonKeyDetailsOfTBDataTbDetailsStatus = 'status';
const String _jsonKeyDetailsOfTBDataTbDetailsCreatedAt = 'created_at';
const String _jsonKeyDetailsOfTBDataTbDetailsUpdatedAt = 'updated_at';
const String _jsonKeyDetailsOfTBDataTbDetailsImage = 'image';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySub = 'category_sub';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubId = 'id';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubCategoryId =
    'category_id';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubComponentId =
    'component_id';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubName = 'name';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubNameNe = 'name_ne';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubOrderBy = 'order_by';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubIsSubCat = 'is_sub_cat';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubIsMedication =
    'is_medication';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubStatus = 'status';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubCreatedAt =
    'created_at';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubUpdatedAt =
    'updated_at';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubContent = 'content';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubContentId = 'id';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubContentSubcategoryId =
    'subcategory_id';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubContentSubcatchildId =
    'subcatchild_id';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubContentContent =
    'content';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubContentContentNe =
    'content_ne';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubContentAudio = 'audio';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubContentAudioNe =
    'audio_ne';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubContentCreatedAt =
    'created_at';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubContentUpdatedAt =
    'updated_at';
const String _jsonKeyDetailsOfTBDataTbDetailsCategorySubContentImage = 'image';

class DetailsOfTBDataTbDetailsCategorySubContent {
/*
{
  "id": 6,
  "subcategory_id": 41,
  "subcatchild_id": 0,
  "content": "<p>Tuberculosis is an infectious disease caused by mycobacterium Tuberculosis. It can be spread from one person to another when TB patient cough and sneeze. Patient who is under treatment cannot spread to others. TB can be cured with the full course of right treatment. People who do not get the right treatment can die from TB.</p>",
  "content_ne": "<p>क्षयरोग एक संक्रामक सरुवा&nbsp;रोग हो जुन&nbsp;माइक्रो व्याक्टेरियम ट्युबरक्लोसिस नामक कीटाणुबाट हुन्छ&nbsp;। क्षयरोग लागेका व्यक्तिले खोक्दा, &nbsp;हाच्छिउं गर्दा हावाको माध्यमबाट यो रोग सर्दछ । क्षयरोगको उपचार गरिरहेका व्यक्तिबाट प्राय: यो रोग सर्दैन । तालिम&nbsp;प्राप्त उपचार सहयोगीको प्रत्यक्ष निगरानीमा पुरा अवधि (६ महिना) उपचार गरेमा यो रोग निको हुन्छ। सही उपचार नगर्ने मानिसहरूको क्षयरोगको&nbsp;कारणले&nbsp;मृत्यु पनि हुन सक्छ।</p>",
  "audio": "",
  "audio_ne": "",
  "created_at": "2021-09-10 09:40:09",
  "updated_at": "2022-01-31 10:16:47",
  "image": "uploads/1643603507.png"
}
*/

  int? id;
  int? subcategoryId;
  int? subcatchildId;
  String? content;
  String? contentNe;
  String? audio;
  String? audioNe;
  String? createdAt;
  String? updatedAt;
  String? image;
  Map<String, dynamic> __origJson = {};

  DetailsOfTBDataTbDetailsCategorySubContent({
    this.id,
    this.subcategoryId,
    this.subcatchildId,
    this.content,
    this.contentNe,
    this.audio,
    this.audioNe,
    this.createdAt,
    this.updatedAt,
    this.image,
  });
  DetailsOfTBDataTbDetailsCategorySubContent.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    id = int.tryParse(json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentId]
            ?.toString() ??
        '');
    subcategoryId = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentSubcategoryId]
                ?.toString() ??
            '');
    subcatchildId = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentSubcatchildId]
                ?.toString() ??
            '');
    content = json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentContent]
        ?.toString();
    contentNe =
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentContentNe]
            ?.toString();
    audio = json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentAudio]
        ?.toString();
    audioNe = json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentAudioNe]
        ?.toString();
    createdAt =
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentCreatedAt]
            ?.toString();
    updatedAt =
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentUpdatedAt]
            ?.toString();
    image = json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentImage]
        ?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentId] = id;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentSubcategoryId] =
        subcategoryId;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentSubcatchildId] =
        subcatchildId;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentContent] = content;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentContentNe] =
        contentNe;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentAudio] = audio;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentAudioNe] = audioNe;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentCreatedAt] =
        createdAt;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentUpdatedAt] =
        updatedAt;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContentImage] = image;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class DetailsOfTBDataTbDetailsCategorySub {
/*
{
  "id": 41,
  "category_id": 15,
  "component_id": 2,
  "name": "What is Tuberculosis?",
  "name_ne": "क्षयरोग भनेको के हो ?",
  "order_by": 1,
  "is_sub_cat": 0,
  "is_medication": 0,
  "status": 1,
  "created_at": "2021-08-25 08:29:53",
  "updated_at": "2021-08-25 08:29:53",
  "content": [
    {
      "id": 6,
      "subcategory_id": 41,
      "subcatchild_id": 0,
      "content": "<p>Tuberculosis is an infectious disease caused by mycobacterium Tuberculosis. It can be spread from one person to another when TB patient cough and sneeze. Patient who is under treatment cannot spread to others. TB can be cured with the full course of right treatment. People who do not get the right treatment can die from TB.</p>",
      "content_ne": "<p>क्षयरोग एक संक्रामक सरुवा&nbsp;रोग हो जुन&nbsp;माइक्रो व्याक्टेरियम ट्युबरक्लोसिस नामक कीटाणुबाट हुन्छ&nbsp;। क्षयरोग लागेका व्यक्तिले खोक्दा, &nbsp;हाच्छिउं गर्दा हावाको माध्यमबाट यो रोग सर्दछ । क्षयरोगको उपचार गरिरहेका व्यक्तिबाट प्राय: यो रोग सर्दैन । तालिम&nbsp;प्राप्त उपचार सहयोगीको प्रत्यक्ष निगरानीमा पुरा अवधि (६ महिना) उपचार गरेमा यो रोग निको हुन्छ। सही उपचार नगर्ने मानिसहरूको क्षयरोगको&nbsp;कारणले&nbsp;मृत्यु पनि हुन सक्छ।</p>",
      "audio": "",
      "audio_ne": "",
      "created_at": "2021-09-10 09:40:09",
      "updated_at": "2022-01-31 10:16:47",
      "image": "uploads/1643603507.png"
    }
  ]
}
*/

  int? id;
  int? categoryId;
  int? componentId;
  String? name;
  String? nameNe;
  int? orderBy;
  int? isSubCat;
  int? isMedication;
  int? status;
  String? createdAt;
  String? updatedAt;
  List<DetailsOfTBDataTbDetailsCategorySubContent?>? content;
  Map<String, dynamic> __origJson = {};

  DetailsOfTBDataTbDetailsCategorySub({
    this.id,
    this.categoryId,
    this.componentId,
    this.name,
    this.nameNe,
    this.orderBy,
    this.isSubCat,
    this.isMedication,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.content,
  });
  DetailsOfTBDataTbDetailsCategorySub.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubId]?.toString() ?? '');
    categoryId = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubCategoryId]
                ?.toString() ??
            '');
    componentId = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubComponentId]
                ?.toString() ??
            '');
    name = json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubName]?.toString();
    nameNe =
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubNameNe]?.toString();
    orderBy = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubOrderBy]?.toString() ??
            '');
    isSubCat = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubIsSubCat]?.toString() ??
            '');
    isMedication = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubIsMedication]
                ?.toString() ??
            '');
    status = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubStatus]?.toString() ??
            '');
    createdAt =
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubCreatedAt]?.toString();
    updatedAt =
        json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubUpdatedAt]?.toString();
    if (json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContent] != null &&
        (json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContent] is List)) {
      final v = json[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContent];
      final arr0 = <DetailsOfTBDataTbDetailsCategorySubContent>[];
      v.forEach((v) {
        arr0.add(DetailsOfTBDataTbDetailsCategorySubContent.fromJson(v));
      });
      content = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubId] = id;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubCategoryId] = categoryId;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubComponentId] = componentId;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubName] = name;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubNameNe] = nameNe;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubOrderBy] = orderBy;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubIsSubCat] = isSubCat;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubIsMedication] =
        isMedication;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubStatus] = status;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubCreatedAt] = createdAt;
    data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubUpdatedAt] = updatedAt;
    if (content != null) {
      final v = content;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyDetailsOfTBDataTbDetailsCategorySubContent] = arr0;
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class DetailsOfTBDataTbDetails {
/*
{
  "id": 15,
  "component_id": 2,
  "name": "About Tuberculosis",
  "name_ne": "क्षयरोग को बारेमा",
  "is_faq": 0,
  "order_by": 0,
  "status": 1,
  "created_at": "2021-08-25 08:28:53",
  "updated_at": "2022-01-31 11:51:27",
  "image": "uploads/1643609187.png",
  "category_sub": [
    {
      "id": 41,
      "category_id": 15,
      "component_id": 2,
      "name": "What is Tuberculosis?",
      "name_ne": "क्षयरोग भनेको के हो ?",
      "order_by": 1,
      "is_sub_cat": 0,
      "is_medication": 0,
      "status": 1,
      "created_at": "2021-08-25 08:29:53",
      "updated_at": "2021-08-25 08:29:53",
      "content": [
        {
          "id": 6,
          "subcategory_id": 41,
          "subcatchild_id": 0,
          "content": "<p>Tuberculosis is an infectious disease caused by mycobacterium Tuberculosis. It can be spread from one person to another when TB patient cough and sneeze. Patient who is under treatment cannot spread to others. TB can be cured with the full course of right treatment. People who do not get the right treatment can die from TB.</p>",
          "content_ne": "<p>क्षयरोग एक संक्रामक सरुवा&nbsp;रोग हो जुन&nbsp;माइक्रो व्याक्टेरियम ट्युबरक्लोसिस नामक कीटाणुबाट हुन्छ&nbsp;। क्षयरोग लागेका व्यक्तिले खोक्दा, &nbsp;हाच्छिउं गर्दा हावाको माध्यमबाट यो रोग सर्दछ । क्षयरोगको उपचार गरिरहेका व्यक्तिबाट प्राय: यो रोग सर्दैन । तालिम&nbsp;प्राप्त उपचार सहयोगीको प्रत्यक्ष निगरानीमा पुरा अवधि (६ महिना) उपचार गरेमा यो रोग निको हुन्छ। सही उपचार नगर्ने मानिसहरूको क्षयरोगको&nbsp;कारणले&nbsp;मृत्यु पनि हुन सक्छ।</p>",
          "audio": "",
          "audio_ne": "",
          "created_at": "2021-09-10 09:40:09",
          "updated_at": "2022-01-31 10:16:47",
          "image": "uploads/1643603507.png"
        }
      ]
    }
  ]
}
*/

  int? id;
  int? componentId;
  String? name;
  String? nameNe;
  int? isFaq;
  int? orderBy;
  int? status;
  String? createdAt;
  String? updatedAt;
  String? image;
  List<DetailsOfTBDataTbDetailsCategorySub?>? categorySub;
  Map<String, dynamic> __origJson = {};

  DetailsOfTBDataTbDetails({
    this.id,
    this.componentId,
    this.name,
    this.nameNe,
    this.isFaq,
    this.orderBy,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.image,
    this.categorySub,
  });
  DetailsOfTBDataTbDetails.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsId]?.toString() ?? '');
    componentId = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsComponentId]?.toString() ?? '');
    name = json[_jsonKeyDetailsOfTBDataTbDetailsName]?.toString();
    nameNe = json[_jsonKeyDetailsOfTBDataTbDetailsNameNe]?.toString();
    isFaq = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsIsFaq]?.toString() ?? '');
    orderBy = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsOrderBy]?.toString() ?? '');
    status = int.tryParse(
        json[_jsonKeyDetailsOfTBDataTbDetailsStatus]?.toString() ?? '');
    createdAt = json[_jsonKeyDetailsOfTBDataTbDetailsCreatedAt]?.toString();
    updatedAt = json[_jsonKeyDetailsOfTBDataTbDetailsUpdatedAt]?.toString();
    image = json[_jsonKeyDetailsOfTBDataTbDetailsImage]?.toString();
    if (json[_jsonKeyDetailsOfTBDataTbDetailsCategorySub] != null &&
        (json[_jsonKeyDetailsOfTBDataTbDetailsCategorySub] is List)) {
      final v = json[_jsonKeyDetailsOfTBDataTbDetailsCategorySub];
      final arr0 = <DetailsOfTBDataTbDetailsCategorySub>[];
      v.forEach((v) {
        arr0.add(DetailsOfTBDataTbDetailsCategorySub.fromJson(v));
      });
      categorySub = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDetailsOfTBDataTbDetailsId] = id;
    data[_jsonKeyDetailsOfTBDataTbDetailsComponentId] = componentId;
    data[_jsonKeyDetailsOfTBDataTbDetailsName] = name;
    data[_jsonKeyDetailsOfTBDataTbDetailsNameNe] = nameNe;
    data[_jsonKeyDetailsOfTBDataTbDetailsIsFaq] = isFaq;
    data[_jsonKeyDetailsOfTBDataTbDetailsOrderBy] = orderBy;
    data[_jsonKeyDetailsOfTBDataTbDetailsStatus] = status;
    data[_jsonKeyDetailsOfTBDataTbDetailsCreatedAt] = createdAt;
    data[_jsonKeyDetailsOfTBDataTbDetailsUpdatedAt] = updatedAt;
    data[_jsonKeyDetailsOfTBDataTbDetailsImage] = image;
    if (categorySub != null) {
      final v = categorySub;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyDetailsOfTBDataTbDetailsCategorySub] = arr0;
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class DetailsOfTBData {
/*
{
  "tb_details": [
    {
      "id": 15,
      "component_id": 2,
      "name": "About Tuberculosis",
      "name_ne": "क्षयरोग को बारेमा",
      "is_faq": 0,
      "order_by": 0,
      "status": 1,
      "created_at": "2021-08-25 08:28:53",
      "updated_at": "2022-01-31 11:51:27",
      "image": "uploads/1643609187.png",
      "category_sub": [
        {
          "id": 41,
          "category_id": 15,
          "component_id": 2,
          "name": "What is Tuberculosis?",
          "name_ne": "क्षयरोग भनेको के हो ?",
          "order_by": 1,
          "is_sub_cat": 0,
          "is_medication": 0,
          "status": 1,
          "created_at": "2021-08-25 08:29:53",
          "updated_at": "2021-08-25 08:29:53",
          "content": [
            {
              "id": 6,
              "subcategory_id": 41,
              "subcatchild_id": 0,
              "content": "<p>Tuberculosis is an infectious disease caused by mycobacterium Tuberculosis. It can be spread from one person to another when TB patient cough and sneeze. Patient who is under treatment cannot spread to others. TB can be cured with the full course of right treatment. People who do not get the right treatment can die from TB.</p>",
              "content_ne": "<p>क्षयरोग एक संक्रामक सरुवा&nbsp;रोग हो जुन&nbsp;माइक्रो व्याक्टेरियम ट्युबरक्लोसिस नामक कीटाणुबाट हुन्छ&nbsp;। क्षयरोग लागेका व्यक्तिले खोक्दा, &nbsp;हाच्छिउं गर्दा हावाको माध्यमबाट यो रोग सर्दछ । क्षयरोगको उपचार गरिरहेका व्यक्तिबाट प्राय: यो रोग सर्दैन । तालिम&nbsp;प्राप्त उपचार सहयोगीको प्रत्यक्ष निगरानीमा पुरा अवधि (६ महिना) उपचार गरेमा यो रोग निको हुन्छ। सही उपचार नगर्ने मानिसहरूको क्षयरोगको&nbsp;कारणले&nbsp;मृत्यु पनि हुन सक्छ।</p>",
              "audio": "",
              "audio_ne": "",
              "created_at": "2021-09-10 09:40:09",
              "updated_at": "2022-01-31 10:16:47",
              "image": "uploads/1643603507.png"
            }
          ]
        }
      ]
    }
  ]
}
*/

  List<DetailsOfTBDataTbDetails?>? tbDetails;
  Map<String, dynamic> __origJson = {};

  DetailsOfTBData({
    this.tbDetails,
  });
  DetailsOfTBData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    if (json[_jsonKeyDetailsOfTBDataTbDetails] != null &&
        (json[_jsonKeyDetailsOfTBDataTbDetails] is List)) {
      final v = json[_jsonKeyDetailsOfTBDataTbDetails];
      final arr0 = <DetailsOfTBDataTbDetails>[];
      v.forEach((v) {
        arr0.add(DetailsOfTBDataTbDetails.fromJson(v));
      });
      tbDetails = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (tbDetails != null) {
      final v = tbDetails;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyDetailsOfTBDataTbDetails] = arr0;
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class DetailsOfTB {
/*
{
  "error": false,
  "message": "list_success",
  "data": {
    "tb_details": [
      {
        "id": 15,
        "component_id": 2,
        "name": "About Tuberculosis",
        "name_ne": "क्षयरोग को बारेमा",
        "is_faq": 0,
        "order_by": 0,
        "status": 1,
        "created_at": "2021-08-25 08:28:53",
        "updated_at": "2022-01-31 11:51:27",
        "image": "uploads/1643609187.png",
        "category_sub": [
          {
            "id": 41,
            "category_id": 15,
            "component_id": 2,
            "name": "What is Tuberculosis?",
            "name_ne": "क्षयरोग भनेको के हो ?",
            "order_by": 1,
            "is_sub_cat": 0,
            "is_medication": 0,
            "status": 1,
            "created_at": "2021-08-25 08:29:53",
            "updated_at": "2021-08-25 08:29:53",
            "content": [
              {
                "id": 6,
                "subcategory_id": 41,
                "subcatchild_id": 0,
                "content": "<p>Tuberculosis is an infectious disease caused by mycobacterium Tuberculosis. It can be spread from one person to another when TB patient cough and sneeze. Patient who is under treatment cannot spread to others. TB can be cured with the full course of right treatment. People who do not get the right treatment can die from TB.</p>",
                "content_ne": "<p>क्षयरोग एक संक्रामक सरुवा&nbsp;रोग हो जुन&nbsp;माइक्रो व्याक्टेरियम ट्युबरक्लोसिस नामक कीटाणुबाट हुन्छ&nbsp;। क्षयरोग लागेका व्यक्तिले खोक्दा, &nbsp;हाच्छिउं गर्दा हावाको माध्यमबाट यो रोग सर्दछ । क्षयरोगको उपचार गरिरहेका व्यक्तिबाट प्राय: यो रोग सर्दैन । तालिम&nbsp;प्राप्त उपचार सहयोगीको प्रत्यक्ष निगरानीमा पुरा अवधि (६ महिना) उपचार गरेमा यो रोग निको हुन्छ। सही उपचार नगर्ने मानिसहरूको क्षयरोगको&nbsp;कारणले&nbsp;मृत्यु पनि हुन सक्छ।</p>",
                "audio": "",
                "audio_ne": "",
                "created_at": "2021-09-10 09:40:09",
                "updated_at": "2022-01-31 10:16:47",
                "image": "uploads/1643603507.png"
              }
            ]
          }
        ]
      }
    ]
  },
  "meta": [
    null
  ]
}
*/

  bool? error;
  String? message;
  DetailsOfTBData? data;
  List<DetailsOfTB>? meta;
  Map<String, dynamic> __origJson = {};

  DetailsOfTB({
    this.error,
    this.message,
    this.data,
    this.meta,
  });
  DetailsOfTB.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    error = json[_jsonKeyDetailsOfTBError];
    message = json[_jsonKeyDetailsOfTBMessage]?.toString();
    data = (json[_jsonKeyDetailsOfTBData] != null &&
            (json[_jsonKeyDetailsOfTBData] is Map))
        ? DetailsOfTBData.fromJson(json[_jsonKeyDetailsOfTBData])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDetailsOfTBError] = error;
    data[_jsonKeyDetailsOfTBMessage] = message;
    if (data != null) {
      data[_jsonKeyDetailsOfTBData] = this.data!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
