///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyLogoutError = 'error';
const String _jsonKeyLogoutMessage = 'message';
const String _jsonKeyLogoutData = 'data';
const String _jsonKeyLogoutMeta = 'meta';
const String _jsonKeyLogoutDataMessage = 'message';

class LogoutData {
/*
{
  "message": "Successfully logged out."
}
*/

  String? message;
  Map<String, dynamic> __origJson = {};

  LogoutData({
    this.message,
  });
  LogoutData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    message = json[_jsonKeyLogoutDataMessage]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyLogoutDataMessage] = message;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class Logout {
/*
{
  "error": false,
  "message": "list_success",
  "data": {
    "message": "Successfully logged out."
  },
  "meta": [
    null
  ]
}
*/

  bool? error;
  String? message;
  LogoutData? data;
  List<Logout>? meta;
  Map<String, dynamic> __origJson = {};

  Logout({
    this.error,
    this.message,
    this.data,
    this.meta,
  });
  Logout.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    error = json[_jsonKeyLogoutError];
    message = json[_jsonKeyLogoutMessage]?.toString();
    data =
        (json[_jsonKeyLogoutData] != null && (json[_jsonKeyLogoutData] is Map))
            ? LogoutData.fromJson(json[_jsonKeyLogoutData])
            : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyLogoutError] = error;
    data[_jsonKeyLogoutMessage] = message;
    if (data != null) {
      data[_jsonKeyLogoutData] = this.data!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
