///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyForgetPasswordError = 'error';
const String _jsonKeyForgetPasswordMessage = 'message';
const String _jsonKeyForgetPasswordData = 'data';
const String _jsonKeyForgetPasswordMeta = 'meta';
const String _jsonKeyForgetPasswordDataMessage = 'message';

class ForgetPasswordData {
/*
{
  "message": "Verification code has been sent to your email address."
}
*/

  String? message;
  Map<String, dynamic> __origJson = {};

  ForgetPasswordData({
    this.message,
  });
  ForgetPasswordData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    message = json[_jsonKeyForgetPasswordDataMessage]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyForgetPasswordDataMessage] = message;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class ForgetPassword {
/*
{
  "error": false,
  "message": "list_success",
  "data": {
    "message": "Verification code has been sent to your email address."
  },
  "meta": [
    null
  ]
}
*/

  bool? error;
  String? message;
  ForgetPasswordData? data;
  List<ForgetPassword>? meta;
  Map<String, dynamic> __origJson = {};

  ForgetPassword({
    this.error,
    this.message,
    this.data,
    this.meta,
  });
  ForgetPassword.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    error = json[_jsonKeyForgetPasswordError];
    message = json[_jsonKeyForgetPasswordMessage]?.toString();
    data = (json[_jsonKeyForgetPasswordData] != null &&
            (json[_jsonKeyForgetPasswordData] is Map))
        ? ForgetPasswordData.fromJson(json[_jsonKeyForgetPasswordData])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyForgetPasswordError] = error;
    data[_jsonKeyForgetPasswordMessage] = message;
    if (data != null) {
      data[_jsonKeyForgetPasswordData] = this.data!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
