///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyDetailsOfDoctorMessage = 'message';
const String _jsonKeyDetailsOfDoctorData = 'data';
const String _jsonKeyDetailsOfDoctorDataDoctorDetails = 'doctor_details';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsId = 'id';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsName = 'name';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsNameNe = 'name_ne';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsSpeciality = 'speciality';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsSpecialityNe = 'speciality_ne';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsRatings = 'ratings';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsRatingsNe = 'ratings_ne';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsExperience = 'experience';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsExperienceNe = 'experience_ne';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsAbout = 'about';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsAboutNe = 'about_ne';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsAvailability = 'availability';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsAvailabilityNe = 'availability_ne';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsCreatedAt = 'created_at';
const String _jsonKeyDetailsOfDoctorDataDoctorDetailsUpdatedAt = 'updated_at';
class DetailsOfDoctorDataDoctorDetails {
/*
{
  "id": 1,
  "name": "Suyash Ghimire",
  "name_ne": "Suyash nepali",
  "speciality": "Virologist, M.D.",
  "speciality_ne": "virus ko doctor",
  "ratings": "4.2",
  "ratings_ne": "char point dui",
  "experience": "5",
  "experience_ne": "5 barsa",
  "about": "Dr. Suyash Ghumire is a top specialist at Nepal Medical College at Kathmandu. He has achieved several awards and recognition for is contribution and service in his own field. He is available for private consultation. ",
  "about_ne": "Suyash euta dami specialist ho",
  "availability": "Mon - Sat (08:30 AM - 09:00 PM)\r\n",
  "availability_ne": "sombar - sani ",
  "created_at": null,
  "updated_at": null
}
*/

  int? id;
  String? name;
  String? nameNe;
  String? speciality;
  String? specialityNe;
  String? ratings;
  String? ratingsNe;
  String? experience;
  String? experienceNe;
  String? about;
  String? aboutNe;
  String? availability;
  String? availabilityNe;
  String? createdAt;
  String? updatedAt;
  Map<String, dynamic> __origJson = {};

  DetailsOfDoctorDataDoctorDetails({
    this.id,
    this.name,
    this.nameNe,
    this.speciality,
    this.specialityNe,
    this.ratings,
    this.ratingsNe,
    this.experience,
    this.experienceNe,
    this.about,
    this.aboutNe,
    this.availability,
    this.availabilityNe,
    this.createdAt,
    this.updatedAt,
  });
  DetailsOfDoctorDataDoctorDetails.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = int.tryParse(json[_jsonKeyDetailsOfDoctorDataDoctorDetailsId]?.toString() ?? '');
    name = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsName]?.toString();
    nameNe = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsNameNe]?.toString();
    speciality = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsSpeciality]?.toString();
    specialityNe = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsSpecialityNe]?.toString();
    ratings = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsRatings]?.toString();
    ratingsNe = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsRatingsNe]?.toString();
    experience = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsExperience]?.toString();
    experienceNe = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsExperienceNe]?.toString();
    about = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsAbout]?.toString();
    aboutNe = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsAboutNe]?.toString();
    availability = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsAvailability]?.toString();
    availabilityNe = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsAvailabilityNe]?.toString();
    createdAt = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsCreatedAt]?.toString();
    updatedAt = json[_jsonKeyDetailsOfDoctorDataDoctorDetailsUpdatedAt]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsId] = id;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsName] = name;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsNameNe] = nameNe;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsSpeciality] = speciality;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsSpecialityNe] = specialityNe;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsRatings] = ratings;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsRatingsNe] = ratingsNe;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsExperience] = experience;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsExperienceNe] = experienceNe;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsAbout] = about;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsAboutNe] = aboutNe;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsAvailability] = availability;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsAvailabilityNe] = availabilityNe;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsCreatedAt] = createdAt;
    data[_jsonKeyDetailsOfDoctorDataDoctorDetailsUpdatedAt] = updatedAt;
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}

class DetailsOfDoctorData {
/*
{
  "doctor_details": [
    {
      "id": 1,
      "name": "Suyash Ghimire",
      "name_ne": "Suyash nepali",
      "speciality": "Virologist, M.D.",
      "speciality_ne": "virus ko doctor",
      "ratings": "4.2",
      "ratings_ne": "char point dui",
      "experience": "5",
      "experience_ne": "5 barsa",
      "about": "Dr. Suyash Ghumire is a top specialist at Nepal Medical College at Kathmandu. He has achieved several awards and recognition for is contribution and service in his own field. He is available for private consultation. ",
      "about_ne": "Suyash euta dami specialist ho",
      "availability": "Mon - Sat (08:30 AM - 09:00 PM)\r\n",
      "availability_ne": "sombar - sani ",
      "created_at": null,
      "updated_at": null
    }
  ]
}
*/

  List<DetailsOfDoctorDataDoctorDetails?>? doctorDetails;
  Map<String, dynamic> __origJson = {};

  DetailsOfDoctorData({
    this.doctorDetails,
  });
  DetailsOfDoctorData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    if (json[_jsonKeyDetailsOfDoctorDataDoctorDetails] != null && (json[_jsonKeyDetailsOfDoctorDataDoctorDetails] is List)) {
      final v = json[_jsonKeyDetailsOfDoctorDataDoctorDetails];
      final arr0 = <DetailsOfDoctorDataDoctorDetails>[];
      v.forEach((v) {
        arr0.add(DetailsOfDoctorDataDoctorDetails.fromJson(v));
      });
      doctorDetails = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (doctorDetails != null) {
      final v = doctorDetails;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyDetailsOfDoctorDataDoctorDetails] = arr0;
    }
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}

class DetailsOfDoctor {
/*
{
  "message": "Data recieved",
  "data": {
    "doctor_details": [
      {
        "id": 1,
        "name": "Suyash Ghimire",
        "name_ne": "Suyash nepali",
        "speciality": "Virologist, M.D.",
        "speciality_ne": "virus ko doctor",
        "ratings": "4.2",
        "ratings_ne": "char point dui",
        "experience": "5",
        "experience_ne": "5 barsa",
        "about": "Dr. Suyash Ghumire is a top specialist at Nepal Medical College at Kathmandu. He has achieved several awards and recognition for is contribution and service in his own field. He is available for private consultation. ",
        "about_ne": "Suyash euta dami specialist ho",
        "availability": "Mon - Sat (08:30 AM - 09:00 PM)\r\n",
        "availability_ne": "sombar - sani ",
        "created_at": null,
        "updated_at": null
      }
    ]
  }
}
*/

  String? message;
  DetailsOfDoctorData? data;
  Map<String, dynamic> __origJson = {};

  DetailsOfDoctor({
    this.message,
    this.data,
  });
  DetailsOfDoctor.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    message = json[_jsonKeyDetailsOfDoctorMessage]?.toString();
    data = (json[_jsonKeyDetailsOfDoctorData] != null && (json[_jsonKeyDetailsOfDoctorData] is Map)) ? DetailsOfDoctorData.fromJson(json[_jsonKeyDetailsOfDoctorData]) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDetailsOfDoctorMessage] = message;
       data[_jsonKeyDetailsOfDoctorData] = this.data!.toJson();
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}
