///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyOTPVerificationError = 'error';
const String _jsonKeyOTPVerificationMessage = 'message';
const String _jsonKeyOTPVerificationData = 'data';
const String _jsonKeyOTPVerificationMeta = 'meta';
const String _jsonKeyOTPVerificationDataMessage = 'message';

class OTPVerificationData {
/*
{
  "message": "Verification code matched."
}
*/

  String? message;
  Map<String, dynamic> __origJson = {};

  OTPVerificationData({
    this.message,
  });
  OTPVerificationData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    message = json[_jsonKeyOTPVerificationDataMessage]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyOTPVerificationDataMessage] = message;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OTPVerification {
/*
{
  "error": false,
  "message": "list_success",
  "data": {
    "message": "Verification code matched."
  },
  "meta": [
    null
  ]
}
*/

  bool? error;
  String? message;
  OTPVerificationData? data;
  List<OTPVerification>? meta;
  Map<String, dynamic> __origJson = {};

  OTPVerification({
    this.error,
    this.message,
    this.data,
    this.meta,
  });
  OTPVerification.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    error = json[_jsonKeyOTPVerificationError];
    message = json[_jsonKeyOTPVerificationMessage]?.toString();
    data = (json[_jsonKeyOTPVerificationData] != null &&
            (json[_jsonKeyOTPVerificationData] is Map))
        ? OTPVerificationData.fromJson(json[_jsonKeyOTPVerificationData])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyOTPVerificationError] = error;
    data[_jsonKeyOTPVerificationMessage] = message;
    if (data != null) {
      data[_jsonKeyOTPVerificationData] = this.data!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
