///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyLoginError = 'error';
const String _jsonKeyLoginMessage = 'message';
const String _jsonKeyLoginData = 'data';
const String _jsonKeyLoginMeta = 'meta';
const String _jsonKeyLoginDataToken = 'token';
const String _jsonKeyLoginDataMessage = 'message';
const String _jsonKeyLoginDataUser = 'user';
const String _jsonKeyLoginDataUserId = 'id';
const String _jsonKeyLoginDataUserName = 'name';
const String _jsonKeyLoginDataUserEmail = 'email';
const String _jsonKeyLoginDataUserEmailVerifiedAt = 'email_verified_at';
const String _jsonKeyLoginDataUserCreatedAt = 'created_at';
const String _jsonKeyLoginDataUserUpdatedAt = 'updated_at';
const String _jsonKeyLoginDataUserPhoneNo = 'phone_no';
const String _jsonKeyLoginDataUserOtpCode = 'otp_code';

class LoginDataUser {
/*
{
  "id": 10,
  "name": "test",
  "email": "avashsth@gmail.com",
  "email_verified_at": null,
  "created_at": "2021-11-15 09:26:08",
  "updated_at": "2021-11-15 09:26:08",
  "phone_no": "982343435",
  "otp_code": null
}
*/

  int? id;
  String? name;
  String? email;
  String? emailVerifiedAt;
  String? createdAt;
  String? updatedAt;
  String? phoneNo;
  String? otpCode;
  Map<String, dynamic> __origJson = {};

  LoginDataUser({
    this.id,
    this.name,
    this.email,
    this.emailVerifiedAt,
    this.createdAt,
    this.updatedAt,
    this.phoneNo,
    this.otpCode,
  });
  LoginDataUser.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = int.tryParse(json[_jsonKeyLoginDataUserId]?.toString() ?? '');
    name = json[_jsonKeyLoginDataUserName]?.toString();
    email = json[_jsonKeyLoginDataUserEmail]?.toString();
    emailVerifiedAt = json[_jsonKeyLoginDataUserEmailVerifiedAt]?.toString();
    createdAt = json[_jsonKeyLoginDataUserCreatedAt]?.toString();
    updatedAt = json[_jsonKeyLoginDataUserUpdatedAt]?.toString();
    phoneNo = json[_jsonKeyLoginDataUserPhoneNo]?.toString();
    otpCode = json[_jsonKeyLoginDataUserOtpCode]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyLoginDataUserId] = id;
    data[_jsonKeyLoginDataUserName] = name;
    data[_jsonKeyLoginDataUserEmail] = email;
    data[_jsonKeyLoginDataUserEmailVerifiedAt] = emailVerifiedAt;
    data[_jsonKeyLoginDataUserCreatedAt] = createdAt;
    data[_jsonKeyLoginDataUserUpdatedAt] = updatedAt;
    data[_jsonKeyLoginDataUserPhoneNo] = phoneNo;
    data[_jsonKeyLoginDataUserOtpCode] = otpCode;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class LoginData {
/*
{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6Ijg1MWVhZDg4ZDUxODE1N2I5Nzc5OWQzNzg5MmNhNGQwZjAwODY2MmI0N2MwNTYyYzNlM2YwYmQzYjQ1ODg3M2UwOGYyZTM1YmQ1ZDM4Yzk3In0.eyJhdWQiOiI1IiwianRpIjoiODUxZWFkODhkNTE4MTU3Yjk3Nzk5ZDM3ODkyY2E0ZDBmMDA4NjYyYjQ3YzA1NjJjM2UzZjBiZDNiNDU4ODczZTA4ZjJlMzViZDVkMzhjOTciLCJpYXQiOjE2Mzc1NjQ5MDcsIm5iZiI6MTYzNzU2NDkwNywiZXhwIjoxNjY5MTAwOTA3LCJzdWIiOiIxMCIsInNjb3BlcyI6W119.ND4iIGtgk3XUtlL7lEu0_swcc5dpay5LfeFp8fOQh2ukfll2iNZYZPJcvp5zmF7Uz8KguIRqft2wcxdshI_Vx7ZjbW7mc1PqL6r06VDt12cHdTdKJW6aqfILJj-t4RCcSn3Ht_awq_F-js9MG2CUfy05LOw6SEZQi3wyExJ0VV6rGSMv5gAcoPhxI9k8Ptm4SJApbldSSHp_qCdE5-gQdN344O66bA5so9gqxGorzG6z8pk1oVMr4ySRe-MQUGJEvxyXOaWmA6vvx0P0TwVU6R4nJDzNfNeff7GS18Qx3KHSsHau_WaRaxXjJQ0lAoqImmctcE-1l-WwiYZjWM49-BDAfe_TZ3wKaNXoW2Haci31wV5R0eOKicx3VeqpTKDgewbMOhC-0N85udcozU_Ta3LtKJKXzm4rRwOcXmxHz93lmB__Y7eiky8ksXJfHe369BtSdOkiORKLf6PUtA4lSIqvQsb99W1yKRyL-C0hOnHEq5xKNtmaY3cYnc0ExUMhJf2IaW103E9w9Sq49z_wHMZlVgHWNjDVY8I9trwOGEuBWPgYPBgPuKLpDt5TR6-_DOlYzQt-b8oBc-MxkZH38J17_3zlVR6tPAJVbsPKvcNwaqONda8lH7REWoEmk9PHBqciRHeDWEIss7TYZz8G8oYKPtV9BEN9TeLjE-gpPK8",
  "message": "Logged in succeed.",
  "user": {
    "id": 10,
    "name": "test",
    "email": "avashsth@gmail.com",
    "email_verified_at": null,
    "created_at": "2021-11-15 09:26:08",
    "updated_at": "2021-11-15 09:26:08",
    "phone_no": "982343435",
    "otp_code": null
  }
}
*/

  String? token;
  String? message;
  LoginDataUser? user;
  Map<String, dynamic> __origJson = {};

  LoginData({
    this.token,
    this.message,
    this.user,
  });
  LoginData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    token = json[_jsonKeyLoginDataToken]?.toString();
    message = json[_jsonKeyLoginDataMessage]?.toString();
    user = (json[_jsonKeyLoginDataUser] != null &&
            (json[_jsonKeyLoginDataUser] is Map))
        ? LoginDataUser.fromJson(json[_jsonKeyLoginDataUser])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyLoginDataToken] = token;
    data[_jsonKeyLoginDataMessage] = message;
    if (user != null) {
      data[_jsonKeyLoginDataUser] = user!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class Login {
/*
{
  "error": false,
  "message": "list_success",
  "data": {
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6Ijg1MWVhZDg4ZDUxODE1N2I5Nzc5OWQzNzg5MmNhNGQwZjAwODY2MmI0N2MwNTYyYzNlM2YwYmQzYjQ1ODg3M2UwOGYyZTM1YmQ1ZDM4Yzk3In0.eyJhdWQiOiI1IiwianRpIjoiODUxZWFkODhkNTE4MTU3Yjk3Nzk5ZDM3ODkyY2E0ZDBmMDA4NjYyYjQ3YzA1NjJjM2UzZjBiZDNiNDU4ODczZTA4ZjJlMzViZDVkMzhjOTciLCJpYXQiOjE2Mzc1NjQ5MDcsIm5iZiI6MTYzNzU2NDkwNywiZXhwIjoxNjY5MTAwOTA3LCJzdWIiOiIxMCIsInNjb3BlcyI6W119.ND4iIGtgk3XUtlL7lEu0_swcc5dpay5LfeFp8fOQh2ukfll2iNZYZPJcvp5zmF7Uz8KguIRqft2wcxdshI_Vx7ZjbW7mc1PqL6r06VDt12cHdTdKJW6aqfILJj-t4RCcSn3Ht_awq_F-js9MG2CUfy05LOw6SEZQi3wyExJ0VV6rGSMv5gAcoPhxI9k8Ptm4SJApbldSSHp_qCdE5-gQdN344O66bA5so9gqxGorzG6z8pk1oVMr4ySRe-MQUGJEvxyXOaWmA6vvx0P0TwVU6R4nJDzNfNeff7GS18Qx3KHSsHau_WaRaxXjJQ0lAoqImmctcE-1l-WwiYZjWM49-BDAfe_TZ3wKaNXoW2Haci31wV5R0eOKicx3VeqpTKDgewbMOhC-0N85udcozU_Ta3LtKJKXzm4rRwOcXmxHz93lmB__Y7eiky8ksXJfHe369BtSdOkiORKLf6PUtA4lSIqvQsb99W1yKRyL-C0hOnHEq5xKNtmaY3cYnc0ExUMhJf2IaW103E9w9Sq49z_wHMZlVgHWNjDVY8I9trwOGEuBWPgYPBgPuKLpDt5TR6-_DOlYzQt-b8oBc-MxkZH38J17_3zlVR6tPAJVbsPKvcNwaqONda8lH7REWoEmk9PHBqciRHeDWEIss7TYZz8G8oYKPtV9BEN9TeLjE-gpPK8",
    "message": "Logged in succeed.",
    "user": {
      "id": 10,
      "name": "test",
      "email": "avashsth@gmail.com",
      "email_verified_at": null,
      "created_at": "2021-11-15 09:26:08",
      "updated_at": "2021-11-15 09:26:08",
      "phone_no": "982343435",
      "otp_code": null
    }
  },
  "meta": [
    null
  ]
}
*/

  bool? error;
  String? message;
  LoginData? data;
  List<Login>? meta;
  Map<String, dynamic> __origJson = {};

  Login({
    this.error,
    this.message,
    this.data,
    this.meta,
  });
  Login.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    error = json[_jsonKeyLoginError];
    message = json[_jsonKeyLoginMessage]?.toString();
    data = (json[_jsonKeyLoginData] != null && (json[_jsonKeyLoginData] is Map))
        ? LoginData.fromJson(json[_jsonKeyLoginData])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyLoginError] = error;
    data[_jsonKeyLoginMessage] = message;
    if (data != null) {
      data[_jsonKeyLoginData] = this.data!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
