///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyDetailsOfHivError = 'error';
const String _jsonKeyDetailsOfHivMessage = 'message';
const String _jsonKeyDetailsOfHivData = 'data';
const String _jsonKeyDetailsOfHivMeta = 'meta';
const String _jsonKeyDetailsOfHivDataHivDetails = 'hiv_details';
const String _jsonKeyDetailsOfHivDataHivDetailsId = 'id';
const String _jsonKeyDetailsOfHivDataHivDetailsComponentId = 'component_id';
const String _jsonKeyDetailsOfHivDataHivDetailsName = 'name';
const String _jsonKeyDetailsOfHivDataHivDetailsNameNe = 'name_ne';
const String _jsonKeyDetailsOfHivDataHivDetailsIsFaq = 'is_faq';
const String _jsonKeyDetailsOfHivDataHivDetailsOrderBy = 'order_by';
const String _jsonKeyDetailsOfHivDataHivDetailsStatus = 'status';
const String _jsonKeyDetailsOfHivDataHivDetailsCreatedAt = 'created_at';
const String _jsonKeyDetailsOfHivDataHivDetailsUpdatedAt = 'updated_at';
const String _jsonKeyDetailsOfHivDataHivDetailsImage = 'image';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySub = 'category_sub';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubId = 'id';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubCategoryId =
    'category_id';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubComponentId =
    'component_id';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubName = 'name';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubNameNe = 'name_ne';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubOrderBy = 'order_by';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubIsSubCat =
    'is_sub_cat';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubIsMedication =
    'is_medication';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubStatus = 'status';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubCreatedAt =
    'created_at';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubUpdatedAt =
    'updated_at';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubContent = 'content';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubContentId = 'id';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubContentSubcategoryId =
    'subcategory_id';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubContentSubcatchildId =
    'subcatchild_id';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubContentContent =
    'content';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubContentContentNe =
    'content_ne';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubContentAudio =
    'audio';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubContentAudioNe =
    'audio_ne';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubContentCreatedAt =
    'created_at';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubContentUpdatedAt =
    'updated_at';
const String _jsonKeyDetailsOfHivDataHivDetailsCategorySubContentImage =
    'image';

class DetailsOfHivDataHivDetailsCategorySubContent {
/*
{
  "id": 51,
  "subcategory_id": 6,
  "subcatchild_id": 0,
  "content": "<p>HIV stands for Human Immunodeficiency Virus.</p>\r\n\r\n<p>It is a virus that can attack the ability of our body to fight against diseases.</p>\r\n\r\n<p>A person infected with HIV may have a weak immune system making them susceptible to<br />\r\nsevere infections and other diseases.</p>",
  "content_ne": "<p>एच. आई. भी को पुरा नाम अंग्रेजीमा Human Immunodefiency Virus हो ।</p>\r\n\r\n<p>यो एक प्रकारको भाईरस हो जसले हाम्रो शरीरको रोग संग लड्न सक्ने क्षमतालाई कमजोर बनाउँछ ।</p>\r\n\r\n<p>एच.आई.भी संक्रमणले हाम्रो शरीरको रोग संग लड्न सक्ने शक्तिलाई कमजोर बनाउँन सक्छ र अन्य रोगहरु लाग्ने जोखिम पनि बढाउन सक्छ।</p>",
  "audio": "",
  "audio_ne": "",
  "created_at": "2021-09-10 10:12:13",
  "updated_at": "2021-09-10 10:12:13",
  "image": null
}
*/

  int? id;
  int? subcategoryId;
  int? subcatchildId;
  String? content;
  String? contentNe;
  String? audio;
  String? audioNe;
  String? createdAt;
  String? updatedAt;
  String? image;
  Map<String, dynamic> __origJson = {};

  DetailsOfHivDataHivDetailsCategorySubContent({
    this.id,
    this.subcategoryId,
    this.subcatchildId,
    this.content,
    this.contentNe,
    this.audio,
    this.audioNe,
    this.createdAt,
    this.updatedAt,
    this.image,
  });
  DetailsOfHivDataHivDetailsCategorySubContent.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    id = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentId]
                ?.toString() ??
            '');
    subcategoryId = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentSubcategoryId]
                ?.toString() ??
            '');
    subcatchildId = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentSubcatchildId]
                ?.toString() ??
            '');
    content = json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentContent]
        ?.toString();
    contentNe =
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentContentNe]
            ?.toString();
    audio = json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentAudio]
        ?.toString();
    audioNe = json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentAudioNe]
        ?.toString();
    createdAt =
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentCreatedAt]
            ?.toString();
    updatedAt =
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentUpdatedAt]
            ?.toString();
    image = json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentImage]
        ?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentId] = id;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentSubcategoryId] =
        subcategoryId;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentSubcatchildId] =
        subcatchildId;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentContent] = content;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentContentNe] =
        contentNe;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentAudio] = audio;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentAudioNe] = audioNe;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentCreatedAt] =
        createdAt;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentUpdatedAt] =
        updatedAt;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContentImage] = image;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class DetailsOfHivDataHivDetailsCategorySub {
/*
{
  "id": 6,
  "category_id": 11,
  "component_id": 1,
  "name": "What is HIV?",
  "name_ne": "एच.आई.भी भनेको के हो?",
  "order_by": 0,
  "is_sub_cat": 0,
  "is_medication": 0,
  "status": 1,
  "created_at": "2021-08-25 08:13:26",
  "updated_at": "2021-08-25 08:13:26",
  "content": [
    {
      "id": 51,
      "subcategory_id": 6,
      "subcatchild_id": 0,
      "content": "<p>HIV stands for Human Immunodeficiency Virus.</p>\r\n\r\n<p>It is a virus that can attack the ability of our body to fight against diseases.</p>\r\n\r\n<p>A person infected with HIV may have a weak immune system making them susceptible to<br />\r\nsevere infections and other diseases.</p>",
      "content_ne": "<p>एच. आई. भी को पुरा नाम अंग्रेजीमा Human Immunodefiency Virus हो ।</p>\r\n\r\n<p>यो एक प्रकारको भाईरस हो जसले हाम्रो शरीरको रोग संग लड्न सक्ने क्षमतालाई कमजोर बनाउँछ ।</p>\r\n\r\n<p>एच.आई.भी संक्रमणले हाम्रो शरीरको रोग संग लड्न सक्ने शक्तिलाई कमजोर बनाउँन सक्छ र अन्य रोगहरु लाग्ने जोखिम पनि बढाउन सक्छ।</p>",
      "audio": "",
      "audio_ne": "",
      "created_at": "2021-09-10 10:12:13",
      "updated_at": "2021-09-10 10:12:13",
      "image": null
    }
  ]
}
*/

  int? id;
  int? categoryId;
  int? componentId;
  String? name;
  String? nameNe;
  int? orderBy;
  int? isSubCat;
  int? isMedication;
  int? status;
  String? createdAt;
  String? updatedAt;
  List<DetailsOfHivDataHivDetailsCategorySubContent?>? content;
  Map<String, dynamic> __origJson = {};

  DetailsOfHivDataHivDetailsCategorySub({
    this.id,
    this.categoryId,
    this.componentId,
    this.name,
    this.nameNe,
    this.orderBy,
    this.isSubCat,
    this.isMedication,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.content,
  });
  DetailsOfHivDataHivDetailsCategorySub.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubId]?.toString() ??
            '');
    categoryId = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubCategoryId]
                ?.toString() ??
            '');
    componentId = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubComponentId]
                ?.toString() ??
            '');
    name = json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubName]?.toString();
    nameNe =
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubNameNe]?.toString();
    orderBy = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubOrderBy]
                ?.toString() ??
            '');
    isSubCat = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubIsSubCat]
                ?.toString() ??
            '');
    isMedication = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubIsMedication]
                ?.toString() ??
            '');
    status = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubStatus]?.toString() ??
            '');
    createdAt = json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubCreatedAt]
        ?.toString();
    updatedAt = json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubUpdatedAt]
        ?.toString();
    if (json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContent] != null &&
        (json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContent] is List)) {
      final v = json[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContent];
      final arr0 = <DetailsOfHivDataHivDetailsCategorySubContent>[];
      v.forEach((v) {
        arr0.add(DetailsOfHivDataHivDetailsCategorySubContent.fromJson(v));
      });
      content = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubId] = id;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubCategoryId] = categoryId;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubComponentId] =
        componentId;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubName] = name;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubNameNe] = nameNe;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubOrderBy] = orderBy;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubIsSubCat] = isSubCat;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubIsMedication] =
        isMedication;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubStatus] = status;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubCreatedAt] = createdAt;
    data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubUpdatedAt] = updatedAt;
    if (content != null) {
      final v = content;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyDetailsOfHivDataHivDetailsCategorySubContent] = arr0;
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class DetailsOfHivDataHivDetails {
/*
{
  "id": 11,
  "component_id": 1,
  "name": "About HIV/AIDS",
  "name_ne": "एच.आई.भी / एड्स को बारे",
  "is_faq": 0,
  "order_by": 0,
  "status": 1,
  "created_at": "2021-08-25 08:11:56",
  "updated_at": "2021-08-25 08:11:56",
  "image": "",
  "category_sub": [
    {
      "id": 6,
      "category_id": 11,
      "component_id": 1,
      "name": "What is HIV?",
      "name_ne": "एच.आई.भी भनेको के हो?",
      "order_by": 0,
      "is_sub_cat": 0,
      "is_medication": 0,
      "status": 1,
      "created_at": "2021-08-25 08:13:26",
      "updated_at": "2021-08-25 08:13:26",
      "content": [
        {
          "id": 51,
          "subcategory_id": 6,
          "subcatchild_id": 0,
          "content": "<p>HIV stands for Human Immunodeficiency Virus.</p>\r\n\r\n<p>It is a virus that can attack the ability of our body to fight against diseases.</p>\r\n\r\n<p>A person infected with HIV may have a weak immune system making them susceptible to<br />\r\nsevere infections and other diseases.</p>",
          "content_ne": "<p>एच. आई. भी को पुरा नाम अंग्रेजीमा Human Immunodefiency Virus हो ।</p>\r\n\r\n<p>यो एक प्रकारको भाईरस हो जसले हाम्रो शरीरको रोग संग लड्न सक्ने क्षमतालाई कमजोर बनाउँछ ।</p>\r\n\r\n<p>एच.आई.भी संक्रमणले हाम्रो शरीरको रोग संग लड्न सक्ने शक्तिलाई कमजोर बनाउँन सक्छ र अन्य रोगहरु लाग्ने जोखिम पनि बढाउन सक्छ।</p>",
          "audio": "",
          "audio_ne": "",
          "created_at": "2021-09-10 10:12:13",
          "updated_at": "2021-09-10 10:12:13",
          "image": null
        }
      ]
    }
  ]
}
*/

  int? id;
  int? componentId;
  String? name;
  String? nameNe;
  int? isFaq;
  int? orderBy;
  int? status;
  String? createdAt;
  String? updatedAt;
  String? image;
  List<DetailsOfHivDataHivDetailsCategorySub?>? categorySub;
  Map<String, dynamic> __origJson = {};

  DetailsOfHivDataHivDetails({
    this.id,
    this.componentId,
    this.name,
    this.nameNe,
    this.isFaq,
    this.orderBy,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.image,
    this.categorySub,
  });
  DetailsOfHivDataHivDetails.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsId]?.toString() ?? '');
    componentId = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsComponentId]?.toString() ?? '');
    name = json[_jsonKeyDetailsOfHivDataHivDetailsName]?.toString();
    nameNe = json[_jsonKeyDetailsOfHivDataHivDetailsNameNe]?.toString();
    isFaq = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsIsFaq]?.toString() ?? '');
    orderBy = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsOrderBy]?.toString() ?? '');
    status = int.tryParse(
        json[_jsonKeyDetailsOfHivDataHivDetailsStatus]?.toString() ?? '');
    createdAt = json[_jsonKeyDetailsOfHivDataHivDetailsCreatedAt]?.toString();
    updatedAt = json[_jsonKeyDetailsOfHivDataHivDetailsUpdatedAt]?.toString();
    image = json[_jsonKeyDetailsOfHivDataHivDetailsImage]?.toString();
    if (json[_jsonKeyDetailsOfHivDataHivDetailsCategorySub] != null &&
        (json[_jsonKeyDetailsOfHivDataHivDetailsCategorySub] is List)) {
      final v = json[_jsonKeyDetailsOfHivDataHivDetailsCategorySub];
      final arr0 = <DetailsOfHivDataHivDetailsCategorySub>[];
      v.forEach((v) {
        arr0.add(DetailsOfHivDataHivDetailsCategorySub.fromJson(v));
      });
      categorySub = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDetailsOfHivDataHivDetailsId] = id;
    data[_jsonKeyDetailsOfHivDataHivDetailsComponentId] = componentId;
    data[_jsonKeyDetailsOfHivDataHivDetailsName] = name;
    data[_jsonKeyDetailsOfHivDataHivDetailsNameNe] = nameNe;
    data[_jsonKeyDetailsOfHivDataHivDetailsIsFaq] = isFaq;
    data[_jsonKeyDetailsOfHivDataHivDetailsOrderBy] = orderBy;
    data[_jsonKeyDetailsOfHivDataHivDetailsStatus] = status;
    data[_jsonKeyDetailsOfHivDataHivDetailsCreatedAt] = createdAt;
    data[_jsonKeyDetailsOfHivDataHivDetailsUpdatedAt] = updatedAt;
    data[_jsonKeyDetailsOfHivDataHivDetailsImage] = image;
    if (categorySub != null) {
      final v = categorySub;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyDetailsOfHivDataHivDetailsCategorySub] = arr0;
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class DetailsOfHivData {
/*
{
  "hiv_details": [
    {
      "id": 11,
      "component_id": 1,
      "name": "About HIV/AIDS",
      "name_ne": "एच.आई.भी / एड्स को बारे",
      "is_faq": 0,
      "order_by": 0,
      "status": 1,
      "created_at": "2021-08-25 08:11:56",
      "updated_at": "2021-08-25 08:11:56",
      "image": "",
      "category_sub": [
        {
          "id": 6,
          "category_id": 11,
          "component_id": 1,
          "name": "What is HIV?",
          "name_ne": "एच.आई.भी भनेको के हो?",
          "order_by": 0,
          "is_sub_cat": 0,
          "is_medication": 0,
          "status": 1,
          "created_at": "2021-08-25 08:13:26",
          "updated_at": "2021-08-25 08:13:26",
          "content": [
            {
              "id": 51,
              "subcategory_id": 6,
              "subcatchild_id": 0,
              "content": "<p>HIV stands for Human Immunodeficiency Virus.</p>\r\n\r\n<p>It is a virus that can attack the ability of our body to fight against diseases.</p>\r\n\r\n<p>A person infected with HIV may have a weak immune system making them susceptible to<br />\r\nsevere infections and other diseases.</p>",
              "content_ne": "<p>एच. आई. भी को पुरा नाम अंग्रेजीमा Human Immunodefiency Virus हो ।</p>\r\n\r\n<p>यो एक प्रकारको भाईरस हो जसले हाम्रो शरीरको रोग संग लड्न सक्ने क्षमतालाई कमजोर बनाउँछ ।</p>\r\n\r\n<p>एच.आई.भी संक्रमणले हाम्रो शरीरको रोग संग लड्न सक्ने शक्तिलाई कमजोर बनाउँन सक्छ र अन्य रोगहरु लाग्ने जोखिम पनि बढाउन सक्छ।</p>",
              "audio": "",
              "audio_ne": "",
              "created_at": "2021-09-10 10:12:13",
              "updated_at": "2021-09-10 10:12:13",
              "image": null
            }
          ]
        }
      ]
    }
  ]
}
*/

  List<DetailsOfHivDataHivDetails?>? hivDetails;
  Map<String, dynamic> __origJson = {};

  DetailsOfHivData({
    this.hivDetails,
  });
  DetailsOfHivData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    if (json[_jsonKeyDetailsOfHivDataHivDetails] != null &&
        (json[_jsonKeyDetailsOfHivDataHivDetails] is List)) {
      final v = json[_jsonKeyDetailsOfHivDataHivDetails];
      final arr0 = <DetailsOfHivDataHivDetails>[];
      v.forEach((v) {
        arr0.add(DetailsOfHivDataHivDetails.fromJson(v));
      });
      hivDetails = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (hivDetails != null) {
      final v = hivDetails;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyDetailsOfHivDataHivDetails] = arr0;
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class DetailsOfHiv {
/*
{
  "error": false,
  "message": "list_success",
  "data": {
    "hiv_details": [
      {
        "id": 11,
        "component_id": 1,
        "name": "About HIV/AIDS",
        "name_ne": "एच.आई.भी / एड्स को बारे",
        "is_faq": 0,
        "order_by": 0,
        "status": 1,
        "created_at": "2021-08-25 08:11:56",
        "updated_at": "2021-08-25 08:11:56",
        "image": "",
        "category_sub": [
          {
            "id": 6,
            "category_id": 11,
            "component_id": 1,
            "name": "What is HIV?",
            "name_ne": "एच.आई.भी भनेको के हो?",
            "order_by": 0,
            "is_sub_cat": 0,
            "is_medication": 0,
            "status": 1,
            "created_at": "2021-08-25 08:13:26",
            "updated_at": "2021-08-25 08:13:26",
            "content": [
              {
                "id": 51,
                "subcategory_id": 6,
                "subcatchild_id": 0,
                "content": "<p>HIV stands for Human Immunodeficiency Virus.</p>\r\n\r\n<p>It is a virus that can attack the ability of our body to fight against diseases.</p>\r\n\r\n<p>A person infected with HIV may have a weak immune system making them susceptible to<br />\r\nsevere infections and other diseases.</p>",
                "content_ne": "<p>एच. आई. भी को पुरा नाम अंग्रेजीमा Human Immunodefiency Virus हो ।</p>\r\n\r\n<p>यो एक प्रकारको भाईरस हो जसले हाम्रो शरीरको रोग संग लड्न सक्ने क्षमतालाई कमजोर बनाउँछ ।</p>\r\n\r\n<p>एच.आई.भी संक्रमणले हाम्रो शरीरको रोग संग लड्न सक्ने शक्तिलाई कमजोर बनाउँन सक्छ र अन्य रोगहरु लाग्ने जोखिम पनि बढाउन सक्छ।</p>",
                "audio": "",
                "audio_ne": "",
                "created_at": "2021-09-10 10:12:13",
                "updated_at": "2021-09-10 10:12:13",
                "image": null
              }
            ]
          }
        ]
      }
    ]
  },
  "meta": [
    null
  ]
}
*/

  bool? error;
  String? message;
  DetailsOfHivData? data;
  List<DetailsOfHiv>? meta;
  Map<String, dynamic> __origJson = {};

  DetailsOfHiv({
    this.error,
    this.message,
    this.data,
    this.meta,
  });
  DetailsOfHiv.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    error = json[_jsonKeyDetailsOfHivError];
    message = json[_jsonKeyDetailsOfHivMessage]?.toString();
    data = (json[_jsonKeyDetailsOfHivData] != null &&
            (json[_jsonKeyDetailsOfHivData] is Map))
        ? DetailsOfHivData.fromJson(json[_jsonKeyDetailsOfHivData])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyDetailsOfHivError] = error;
    data[_jsonKeyDetailsOfHivMessage] = message;
    if (data != null) {
      data[_jsonKeyDetailsOfHivData] = this.data!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
