///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyHotlineNumbersMessage = 'message';
const String _jsonKeyHotlineNumbersData = 'data';
const String _jsonKeyHotlineNumbersDataHotline = 'hotline';
const String _jsonKeyHotlineNumbersDataHotlineId = 'id';
const String _jsonKeyHotlineNumbersDataHotlineName = 'name';
const String _jsonKeyHotlineNumbersDataHotlineAddress = 'address';
const String _jsonKeyHotlineNumbersDataHotlineContactNo = 'contact_no';
class HotlineNumbersDataHotline {
/*
{
  "id": 1,
  "name": "Grande International Hospital",
  "address": "Tokha",
  "contact_no": "15159266"
}
*/

  int? id;
  String? name;
  String? address;
  String? contactNo;
  Map<String, dynamic> __origJson = {};

  HotlineNumbersDataHotline({
    this.id,
    this.name,
    this.address,
    this.contactNo,
  });
  HotlineNumbersDataHotline.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = int.tryParse(json[_jsonKeyHotlineNumbersDataHotlineId]?.toString() ?? '');
    name = json[_jsonKeyHotlineNumbersDataHotlineName]?.toString();
    address = json[_jsonKeyHotlineNumbersDataHotlineAddress]?.toString();
    contactNo = json[_jsonKeyHotlineNumbersDataHotlineContactNo]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyHotlineNumbersDataHotlineId] = id;
    data[_jsonKeyHotlineNumbersDataHotlineName] = name;
    data[_jsonKeyHotlineNumbersDataHotlineAddress] = address;
    data[_jsonKeyHotlineNumbersDataHotlineContactNo] = contactNo;
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}

class HotlineNumbersData {
/*
{
  "hotline": [
    {
      "id": 1,
      "name": "Grande International Hospital",
      "address": "Tokha",
      "contact_no": "15159266"
    }
  ]
}
*/

  List<HotlineNumbersDataHotline?>? hotline;
  Map<String, dynamic> __origJson = {};

  HotlineNumbersData({
    this.hotline,
  });
  HotlineNumbersData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    if (json[_jsonKeyHotlineNumbersDataHotline] != null && (json[_jsonKeyHotlineNumbersDataHotline] is List)) {
      final v = json[_jsonKeyHotlineNumbersDataHotline];
      final arr0 = <HotlineNumbersDataHotline>[];
      v.forEach((v) {
        arr0.add(HotlineNumbersDataHotline.fromJson(v));
      });
      hotline = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (hotline != null) {
      final v = hotline;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data[_jsonKeyHotlineNumbersDataHotline] = arr0;
    }
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}

class HotlineNumbers {
/*
{
  "message": "Data recieved",
  "data": {
    "hotline": [
      {
        "id": 1,
        "name": "Grande International Hospital",
        "address": "Tokha",
        "contact_no": "15159266"
      }
    ]
  }
}
*/

  String? message;
  HotlineNumbersData? data;
  Map<String, dynamic> __origJson = {};

  HotlineNumbers({
    this.message,
    this.data,
  });
  HotlineNumbers.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    message = json[_jsonKeyHotlineNumbersMessage]?.toString();
    data = (json[_jsonKeyHotlineNumbersData] != null && (json[_jsonKeyHotlineNumbersData] is Map)) ? HotlineNumbersData.fromJson(json[_jsonKeyHotlineNumbersData]) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyHotlineNumbersMessage] = message;
    if (data != null) {
      data[_jsonKeyHotlineNumbersData] = this.data!.toJson();
    }
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}
